version: '3.8'
services:
  web:
    build: ./src
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env.example

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: .env.example

  elasticsearch:
    image: elasticsearch:7.13.0
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  redis:
    image: "redis:alpine"

  celery:
    build: ./src
    command: celery -A config worker -l info
    volumes:
      - ./src/app:/app
    depends_on:
      - db
      - redis
    env_file: .env.example
volumes:
  postgres_data:
  elastic_data:
