# Generated by Django 4.1.3 on 2022-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('u', 'User'), ('l', 'Librarian')], default='u', max_length=1),
        ),
    ]
