# Generated by Django 4.1.3 on 2022-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_roles_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('L', 'Librarian')], default='U', max_length=1),
        ),
    ]
